# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8327ff0109680343a457284b1f19c8ff"
name = "shpfy-create-app"
handle = "shpfy-create-app"
application_url = "https://d1p8thm4m851t1.cloudfront.net/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://d1p8thm4m851t1.cloudfront.net/auth/callback", "https://d1p8thm4m851t1.cloudfront.net/auth/shopify/callback" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
